// Shows the name of a KWS class on the Nexys A7's eight 7-segment digits, left-aligned.
// The text per class comes from kws_pkg::CLASS_TEXT (generated by python/kws/export.py).
// Segments and anodes are active low. seg = {g, f, e, d, c, b, a}.
module seg7_word
  import kws_pkg::*;
(
  input  logic       clk,
  input  logic       show,        // blank the display until the first result
  input  logic [3:0] class_idx,
  output logic [6:0] seg,
  output logic       dp,
  output logic [7:0] an
);
  // The class names come from the generated package (python/kws/export.py).
  function automatic logic [63:0] word(input logic [3:0] c);
    return c < 4'(N_CLASSES) ? CLASS_TEXT[c] : "--------";
  endfunction

  // Best-effort letter shapes, active high {g, f, e, d, c, b, a}.
  function automatic logic [6:0] glyph(input logic [7:0] ch);
    unique case (ch)
      "A":     return 7'h77;
      "B":     return 7'h7C;  // b
      "C":     return 7'h39;
      "D":     return 7'h5E;  // d
      "E":     return 7'h79;
      "F":     return 7'h71;
      "G":     return 7'h3D;
      "H":     return 7'h76;
      "I":     return 7'h30;
      "J":     return 7'h1E;
      "K":     return 7'h75;
      "L":     return 7'h38;
      "N":     return 7'h54;  // n
      "O":     return 7'h3F;
      "P":     return 7'h73;
      "Q":     return 7'h67;  // q
      "R":     return 7'h50;  // r
      "S":     return 7'h6D;
      "T":     return 7'h78;  // t
      "U":     return 7'h3E;
      "V":     return 7'h3E;  // same as U
      "W":     return 7'h1C;  // u, the closest a 7-segment digit gets
      "Y":     return 7'h6E;
      "Z":     return 7'h5B;  // like a 2
      "-":     return 7'h40;
      default: return 7'h00;
    endcase
  endfunction

  // Scan one digit every 2^14 cycles (~6 kHz at 100 MHz, ~760 Hz per digit).
  // Registered step by step (word, character, glyph): the display has time, the clock doesn't.
  logic [16:0] scan;
  logic [2:0]  digit, digit_q;
  logic [63:0] text;
  logic [7:0]  ch;
  logic        show_q, show_qq;

  assign digit = scan[16:14];

  always_ff @(posedge clk) begin
    scan    <= scan + 1'b1;
    text    <= word(class_idx);
    show_q  <= show;
    ch      <= text[8*digit +: 8];
    digit_q <= digit;
    show_qq <= show_q;
    an      <= ~(8'd1 << digit_q);
    seg     <= show_qq ? ~glyph(ch) : 7'h7F;
  end

  assign dp = 1'b1;
endmodule
