"""Export the integer model for the RTL, plus golden vectors for the testbenches.

    uv run python -m kws.export

Writes:
  rtl/gen/kws_pkg.sv     constants (layer table, ROM bases, widths) shared with the RTL
  rtl/gen/*.hex          ROM contents for $readmemh (fe_*.hex: mic path and audio frontend,
                         see mic_model.py and fixed_frontend.py)
  build/vectors/         golden inputs/outputs for a few test clips, plus the full test set

Memory layouts (P = LANES channels per word, lane i in bits [8i+7:8i]):
  activations  word (h*W + w)*G + g  holds channels 16g..16g+15 of pixel (h, w)
  stem weights word g*40 + (kh*4 + kw)  lane i = w[16g+i, 0, kh, kw]
  dw weights   word g*9  + (kh*3 + kw)  lane i = w[16g+i, 0, kh, kw]
  pw weights   word g*64 + ci           lane i = w[16g+i, ci]
  bias/shift   word layer*G + g         lane i = value for channel 16g+i

bias.hex holds bias + 2^(shift-1): the round-half-up constant of the requantization
is pre-added, so the hardware requantizes with a plain arithmetic right shift.
"""

import numpy as np
import torch

from .config import CKPT_DIR, CLASSES, ROOT
from .data import Split
from .features import LogMel
from .fixed_frontend import EPS, HANN_Q15, LOG2_LUT, MEL_Q8, TW_IM, TW_RE, offset_q6
from .mic_model import CIC_N, CIC_R, FIR_D, FIR_Q17, MAX_GAIN
from .quant import int_forward, quantize_input

LANES = 16
CHANNELS = 64
GROUPS = CHANNELS // LANES
H_OUT, W_OUT = 25, 20
N_VECTOR_CLIPS = 8

GEN_DIR = ROOT / "rtl" / "gen"
VEC_DIR = ROOT / "build" / "vectors"


def to_hex_words(values: np.ndarray, bits: int) -> list[str]:
    """(N, lanes) integers -> N hex lines, lane 0 in the least significant bits."""
    mask = (1 << bits) - 1
    digits = (bits + 3) // 4
    lines = []
    for row in values.astype(np.int64):
        word = 0
        for i, v in enumerate(row):
            word |= (int(v) & mask) << (bits * i)
        lines.append(f"{word:0{digits * len(row)}x}")
    return lines


def write_hex(name, lines, directory=GEN_DIR):
    directory.mkdir(parents=True, exist_ok=True)
    (directory / name).write_text("\n".join(lines) + "\n")


def pack_weights(p):
    """Conv weights (64, cin/groups, kh, kw) -> (words, LANES) in the ROM order above."""
    w = p["w"].numpy()
    if p["groups"] == 1 and w.shape[1] > 1:  # pointwise: (64, 64, 1, 1)
        w = w[:, :, 0, 0].reshape(GROUPS, LANES, CHANNELS)
    else:  # stem or depthwise: (64, 1, kh, kw)
        w = w.reshape(GROUPS, LANES, -1)
    return w.transpose(0, 2, 1).reshape(-1, LANES)


def pack_acts(a):
    """Activation map (64, H, W) -> (H*W*GROUPS, LANES)."""
    return a.numpy().transpose(1, 2, 0).reshape(-1, LANES)


def layer_kind(p):
    if p["w"].shape[2:] == (10, 4):
        return "STEM"
    return "DW" if p["groups"] > 1 else "PW"


def write_frontend_roms():
    """Mic path + frontend ROMs. Returns the number of mel ROM entries."""
    write_hex("fe_fir.hex", to_hex_words(FIR_Q17.reshape(-1, 1), 18))
    write_hex("fe_hann.hex", to_hex_words(HANN_Q15.reshape(-1, 1), 16))
    write_hex("fe_twiddle.hex", to_hex_words(np.stack([TW_RE, TW_IM], 1), 18))
    write_hex("fe_log2.hex", to_hex_words(LOG2_LUT.reshape(-1, 1), 7))
    # Mel entries in band order: {last_in_band, weight(9), bin(9)}.
    entries = []
    for m in range(MEL_Q8.shape[1]):
        nz = np.nonzero(MEL_Q8[:, m])[0]
        for j, k in enumerate(nz):
            entries.append((int(j == len(nz) - 1) << 18) | (int(MEL_Q8[k, m]) << 9) | int(k))
    write_hex("fe_mel.hex", to_hex_words(np.array(entries).reshape(-1, 1), 19))
    return len(entries)


def write_package(params, bases, n_mel_entries):
    kinds = [layer_kind(p) for p in params["layers"]]
    shifts = torch.cat([p["shift"] for p in params["layers"]])
    assert 1 <= int(shifts.min()) and int(shifts.max()) < 16, "shift must fit in 4 bits"
    n = len(kinds)
    kind_list = ", ".join(f"L_{k}" for k in kinds)
    base_list = ", ".join(str(b) for b in bases)
    classes = ", ".join(f'"{c.strip("_")}"' for c in CLASSES)
    (GEN_DIR / "kws_pkg.sv").write_text(f"""\
// Generated by python/kws/export.py. Do not edit.
package kws_pkg;
  localparam int LANES      = {LANES};
  localparam int CHANNELS   = {CHANNELS};
  localparam int GROUPS     = {GROUPS};
  localparam int IN_H       = 49;
  localparam int IN_W       = 40;
  localparam int OUT_H      = {H_OUT};
  localparam int OUT_W      = {W_OUT};
  localparam int N_LAYERS   = {n};
  localparam int N_CLASSES  = {len(CLASSES)};
  localparam int WROM_WORDS = {bases[-1] + len(pack_weights(params['layers'][-1]))};
  localparam int ACT_WORDS  = OUT_H * OUT_W * GROUPS;

  typedef enum logic [1:0] {{L_STEM, L_DW, L_PW}} layer_kind_t;

  // Index 0 is the first layer.
  localparam layer_kind_t LAYER_KIND [N_LAYERS] = '{{{kind_list}}};
  localparam int          LAYER_WBASE[N_LAYERS] = '{{{base_list}}};

  // For reference only (e.g. testbench printouts): {classes}

  // Mic path (python/kws/mic_model.py)
  localparam int CIC_R       = {CIC_R};
  localparam int CIC_N       = {CIC_N};
  localparam int FIR_D       = {FIR_D};
  localparam int FIR_TAPS    = {len(FIR_Q17)};
  localparam int MAX_GAIN    = {MAX_GAIN};

  // Audio frontend (python/kws/fixed_frontend.py)
  localparam int FFT_N       = 512;
  localparam int HOP         = 320;
  localparam int N_MELS      = IN_W;
  localparam int MEL_ENTRIES = {n_mel_entries};
  localparam longint FE_EPS  = {EPS};
  localparam int FE_OFFSET   = {offset_q6(params["mean"], params["f_in"])};  // Q6, model-specific
endpackage
""")


def main():
    params = torch.load(CKPT_DIR / "dscnn_int8.pt")

    # ROMs
    packed = [pack_weights(p) for p in params["layers"]]
    bases = np.cumsum([0] + [len(w) for w in packed[:-1]]).tolist()
    write_hex("weights.hex", to_hex_words(np.concatenate(packed), 8))
    write_hex("bias.hex", to_hex_words(np.concatenate([
        (p["b"].long() + (1 << (p["shift"].long() - 1))).numpy().reshape(GROUPS, LANES)
        for p in params["layers"]]), 32))
    write_hex("shift.hex", to_hex_words(
        np.concatenate([p["shift"].numpy().reshape(GROUPS, LANES) for p in params["layers"]]), 4))
    write_hex("fc_w.hex", to_hex_words(params["fc_w"].numpy().reshape(-1, 1), 8))
    write_hex("fc_b.hex", to_hex_words(params["fc_b"].numpy().reshape(-1, 1), 32))
    write_package(params, bases, write_frontend_roms())

    # Test-set features, computed on CPU so they are reproducible.
    frontend = LogMel()
    frontend.load_state_dict(torch.load(CKPT_DIR / "dscnn_float.pt")["frontend"])
    test = Split("test", torch.device("cpu"))
    feats, labels = [], []
    with torch.no_grad():
        for x, y in test.batches(512):
            feats.append(quantize_input((frontend.raw(x) - params["mean"]).unsqueeze(1), params["f_in"]))
            labels.append(y)
    feats, labels = torch.cat(feats), torch.cat(labels)

    logits = torch.cat([int_forward(params, f) for f in feats.split(512)])
    preds = logits.argmax(1)
    print(f"integer model on exported test features: {(preds == labels).float().mean():.4f} "
          f"({len(labels)} clips)")

    # Full test set, for long-running end-to-end simulation / on-board runs.
    VEC_DIR.mkdir(parents=True, exist_ok=True)
    feats.squeeze(1).numpy().astype(np.int8).tofile(VEC_DIR / "test_features.bin")
    np.stack([labels.numpy(), preds.numpy()], 1).astype(np.uint8).tofile(VEC_DIR / "test_labels_preds.bin")

    # Per-layer golden vectors for a few clips, one per class where possible.
    picks = [int(torch.nonzero(labels == c)[0]) for c in range(len(CLASSES))][:N_VECTOR_CLIPS]
    for n, i in enumerate(picks):
        d = VEC_DIR / f"clip{n}"
        x = feats[i : i + 1]
        lg, acts, pooled = int_forward(params, x, return_acts=True)
        write_hex("input.hex", to_hex_words(x.flatten().numpy().reshape(-1, 1), 8), d)
        for l, a in enumerate(acts):
            write_hex(f"layer{l}.hex", to_hex_words(pack_acts(a[0]), 8), d)
        write_hex("pooled.hex", to_hex_words(pooled[0].numpy().reshape(-1, 1), 32), d)
        write_hex("logits.hex", to_hex_words(lg[0].numpy().reshape(-1, 1), 32), d)
        (d / "class.txt").write_text(f"{int(lg.argmax())} {int(labels[i])}\n")
    print(f"wrote ROMs to {GEN_DIR.relative_to(ROOT)} and {len(picks)} golden clips to "
          f"{VEC_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
